#!/usr/bin/env node
// Vendor tool: generates RSA keypair for license signing
// NOT shipped with the installer

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 4096,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
});

const outDir = path.join(__dirname, '..', 'keys');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

fs.writeFileSync(path.join(outDir, 'private.pem'), privateKey);
fs.writeFileSync(path.join(outDir, 'public.pem'), publicKey);

console.log('RSA-4096 keypair generated in keys/ directory');
console.log('  keys/private.pem  — KEEP SECRET, use for signing licenses');
console.log('  keys/public.pem   — Embed in server/license/publicKey.js');

// Also write the publicKey.js file
const publicKeyJs = `// Auto-generated — do not edit manually
// Generated by: node tools/generate-keypair.js
const PUBLIC_KEY = \`${publicKey.trim()}\`;

module.exports = PUBLIC_KEY;
`;

fs.writeFileSync(path.join(__dirname, '..', 'server', 'license', 'publicKey.js'), publicKeyJs);
console.log('\nUpdated server/license/publicKey.js with the new public key');
